### ISSUE TITLE
Some friends do not show up

### ISSUE THREAD

**Issue by costis-t** [sqren/fb-sleep-stats#115]
I can only see or search for some of my friends and not all of them.

Should it work for every Facebook friend or for specific ones?
Should I tell to my friend I want to track to activate a specific setting, perhaps in his Facebook privacy tab?
Also, how do I track myself?

**Comment by sorenlouv** [comment]
Hi @costis-t,

> Also, how do I track myself?

Since this tool will make you appear as always online, you can't track yourself. You need to connect your normal Facebook profile with an alternative profile you have created, and do the tracking from there.

> Should it work for every Facebook friend or for specific ones?

I actually don't which friends' statuses Facebook display anymore - it used to be all of your friends but they might have started limiting it.

**Comment by costis-t** [comment]
Yes, that's right @sqren, thanks!
Also, Facebook friends show up after their first login to facebook messenger after the fb-sleep-stats scraper has started. So I close this issue.
